services:

  _defaults:
    public: false
    autowire: true

  OxidAcademy\GraphQL\Category\:
    resource: 'src/*'
    exclude: 'src/**/{DataType,Exception,Infrastructure}'
    public: true

  OxidAcademy\GraphQL\Category\Shared\Service\NamespaceMapper:
    class: OxidAcademy\GraphQL\Category\Shared\Service\NamespaceMapper
    tags: ['graphql_namespace_mapper']

